version: '2.1'
services:
  saml-proxy:
    build:
      context: ../.
      dockerfile: saml-proxy/Dockerfile
    ports:
      - "7000:7000"
    network_mode: "host"
    command: '--config dev-config.json'
